#! /bin/bash

if [ "$1" == "" ]; then
    echo "Link do vídeo:"
    read LINK
    youtube-dl -f best --no-cache-dir -i --audio-format mp3 --extract-audio --audio-quality 0 --yes-playlist $LINK
else
    echo $1
    youtube-dl -f best --no-cache-dir -i --audio-format mp3 --extract-audio --audio-quality 0 --yes-playlist $1
fi
